# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:          /blog/:year/:month/:day/:title/

# Setup
title:            Felix Duvallet
tagline:          'Roboticist'
description:      'Robotics, Machine Learning, and Mountains.'
url:              http://www.felixd.com
baseurl:          /

author:
  name:           'Felix Duvallet'
  url:            http://www.felixd.com
  github:         https://github.com/felixduvallet/
  linkedin:       https://www.linkedin.com/in/felixduvallet

paginate:         3
paginate_path: "/blog/page:num"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/felixduvallet
