# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:          /blog/:year/:month/:day/:title/

# Setup
title:            Felix Duvallet
tagline:          'Roboticist'
description:      'Robotics, Machine Learning, and Mountains.'
url:              http://www.felixd.com
baseurl:          /

author:
  name:           'Felix Duvallet'
  url:            http://www.felixd.com

paginate:         1
paginate_path: "/blog/page:num"

# Custom vars
version:          1.0

github:
  repo:           https://github.com/felixduvallet/felixduvallet.github.io
